spring:
  servlet:
    multipart:
      enabled: true

  application:
    name: api

  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  #    url: jdbc:postgresql://localhost:5432/comdao
  #    username: test_user
  #    password: test123

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  jackson:
    property-naming-strategy: SNAKE_CASE

  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: ae2b0c001@smtp-brevo.com
    password: ${BREVO_APP_PASSWORD}
    from: ${FROM_EMAIL}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



app:
  security:
    password-change-interval-days: 30

  jwt:
    secret-key: ${HASHING_SECRET}
    #    secret-key: ouu7ZMNd9DwnBv8fII4aF1XV9VqwpfH3rbrKRdNMhgfuoZR3U1IGNO787tRrTHI4pC2Y2oKfgh62amnwRAzWW4
    expire-duration-minutes: 120

  admin:
    name: ${ADMIN_NAME}
    username: ${ADMIN_USERNAME}
    email: ${ADMIN_EMAIL}
    phone: ${ADMIN_PHONE}
    password: ${ADMIN_PASSWORD}
  #    name: ADMIN
  #    username: __admin__
  #    email: you.can.never@find.this.email
  #    phone: '0000000000'
  #    password: 12345678

  api-base-url: ${BACKEND_URL}
  s3-base-url: ${S3_URL}

  reward-to-pay-ratio: 0.001


minio:
  url: ${MINIO_URL}
  access-key: ${MINIO_USER}
  secret-key: ${MINIO_PASSWORD}
  buckets: ${MINIO_BUCKETS}
#  url: http://localhost:9000
#  access-key: ${MINIO_USER}
#  secret-key: ${MINIO_PASSWORD}
#  buckets: ${MINIO_BUCKETS}

payos:
  client-id: ${PAYOS_CLIENT_ID}
  api-key: ${PAYOS_API_KEY}
  checksum-key: ${PAYOS_CHECKSUM_KEY}